server:
  port: 8080

log:
  destination: 127.0.0.1

springdoc:
  api-docs:
    path: /service/api-docs
  swagger-ui:
    path: /service/swagger-ui.html

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  rabbitmq:
    host: 127.0.0.1
    username: rabbit
    password: qwesda
